Ap204_Pronia/Models/Color.cs
using System.Collections.Generic;

namespace Ap204_Pronia.Models
{
    public class Color
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Plant> Plants { get; set; }
    }
}

Ap204_Pronia/Areas/ProniaAdmin/Controllers/ColorController.cs
using Microsoft.AspNetCore.Mvc;
using Ap204_Pronia.DAL;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Ap204_Pronia.Areas.ProniaAdmin.Controllers
{
    [Area("ProniaAdmin")]
    public class ColorController : Controller
    {


        private readonly AppDbContext _context;

        public ColorController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            List<Models.Color> colors = await _context.Colors.ToListAsync();
            return View(colors);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Models.Color color)
        {
            if (!ModelState.IsValid) return View();
            await _context.Colors.AddAsync(color);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Detail(int id)
        {
            Models.Color color = await _context.Colors.FirstOrDefaultAsync(s => s.Id == id);
            if (color == null) return NotFound();
            return View(color);
        }

        public async Task<IActionResult> Edit(int id)
        {
            Models.Color color = await _context.Colors.FirstOrDefaultAsync(s => s.Id == id);
            if (color == null) return NotFound();
            return View(color);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Edit(int id, Models.Color color)
        {

            Models.Color existedColor = await _context.Colors.FirstOrDefaultAsync(s => s.Id == id);
            if (existedColor == null) return NotFound();
            if (id != color.Id) return BadRequest();

            existedColor.Name = color.Name;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            Models.Color color = await _context.Colors.FirstOrDefaultAsync(s => s.Id == id);
            if (color == null) return NotFound();
            return View(color);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteSize(int id)
        {
            Models.Color color = await _context.Colors.FirstOrDefaultAsync(s => s.Id == id);
            if (color == null) return NotFound();

            _context.Colors.Remove(color);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }

}

Ap204_Pronia/Areas/ProniaAdmin/Views/Color/Create.cshtml
@using Ap204_Pronia.Models
@model Color
@{
    ViewData["Title"] = "Create";
}

<form method="post" class="form form-control mb-3">
   <div>
     <label class="mb-2" >Color Name:</label>
    <input asp-for="Name" class="form form-control border border-info mb-2" type="text"/>
    <span class="text-danger" asp-validation-for="Name"></span>
   </div>
   <div>
       <button type="submit" class="btn btn-dark"> Create Color</button>
   </div>
</form>

Ap204_Pronia/Areas/ProniaAdmin/Views/Color/Delete.cshtml
@using Ap204_Pronia.Models;
@model Color;

@{
    ViewData["Title"] = "Delete";
}

<div>
    <div>
        <h4>
            Id
        </h4>
        <p>
            @Model.Id
        </p>
    </div>
    <div>
        <h4>
            Name
        </h4>
        <p>
            @Model.Name
        </p>
    </div>
</div>


<form method="post" class="mt-4">
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

Ap204_Pronia/Areas/ProniaAdmin/Views/Color/Detail.cshtml
@using Ap204_Pronia.Models
@model Color
@{
    ViewData["Title"] = "Detail";
}
<div>
    <div>
        <h2>Id:  @Model.Id</h2>
      
    </div>
    <div>
         <h2>Name:   @Model.Name </h2>
       
    </div>
</div>

Ap204_Pronia/Areas/ProniaAdmin/Views/Color/Edit.cshtml
@using Ap204_Pronia.Models
@model Color
@{
    ViewData["Title"] = "Edit";
}

<form method="post" class="form form-control mb-3">
   <div>
     <label class="mb-2" >Color Name:</label>
    <input asp-for="Name" class="form form-control border border-info mb-2" type="text"/>
    <span class="text-danger" asp-validation-for="Name"></span>
   </div>
   <div>
       <button type="submit" class="btn btn-dark"> Edit Color</button>
   </div>
</form>

Ap204_Pronia/Areas/ProniaAdmin/Views/Color/Index.cshtml
@using Ap204_Pronia.Models
@model List<Color>
@{
    ViewData["Title"] = "IndexColor";
}

<div class="table-responsive pt-3">
    <a style="color:white;font-size:20px" asp-controller="Color" asp-action="create" class="mb-3 btn btn-success">Create Color</a>
    <table class="table table-dark">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Name
                </th>
                <th>
                    Settings
                </th>

            </tr>
        </thead>
        <tbody>
            @foreach (var color in Model)
            {
                <tr>
                    <td>
                        @color.Id
                    </td>
                    <td>
                        @color.Name
                    </td>
                    <td>
                        <div class="d-flex">
                            <div class="detail">
                                <a asp-controller="Color" asp-action="Detail" asp-route-id="@color.Id" class="btn btn-primary"><i class="mdi mdi-details"></i></a>
                            </div>
                            <div class="edit">
                                <a asp-controller="Color" asp-action="Edit" asp-route-id="@color.Id" class="btn btn-warning">
                                    <i class="mdi mdi-tooltip-edit"></i>
                                </a>
                            </div>
                            <div class="delete">
                                <a asp-controller="Color" asp-action="Delete" asp-route-id="@color.Id" class="btn btn-danger"> <i class="mdi mdi-delete-forever"></i></a>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>