Ap204_Pronia/Models/Plant.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading.Tasks;

namespace Ap204_Pronia.Models
{
    public class Plant
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [Column(TypeName = "decimal(6,2)")]
        public decimal Price { get; set; }
        public string Description { get; set; }
        public string SKUCode { get; set; }
        public string Shipping { get; set; }
        public string Request { get; set; }
        public string Guarantee { get; set; }
        public int? ColorId { get; set; }
        public Color Color { get; set; }
        public int? SizeId { get; set; }
        public Size Size { get; set; }

        public List<PlantImage> PlantImages { get; set; }
        public List<PlantCategory> PlantCategories { get; set; }


        [NotMapped]
        public IFormFile MainImage { get; set; }
        [NotMapped]
        public List< IFormFile> AnotherImage { get; set; }
        [NotMapped]

        public List<int> ImageIds { get; set; }

        [NotMapped]

        public List<int> CategoryIds { get; set; }
    }
}

Ap204_Pronia/Areas/ProniaAdmin/Controllers/PlantController.cs
using Ap204_Pronia.DAL;
using Ap204_Pronia.Exntention;
using Ap204_Pronia.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;


namespace Ap204_Pronia.Areas.ProniaAdmin.Controllers
{
    [Area("ProniaAdmin")]
    public class PlantController : Controller
    {
        private AppDbContext _context;
        private  IWebHostEnvironment _env;

        public PlantController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env =env;

        }
        public async Task<IActionResult> Index()
        {
            List<Plant> plants = await _context.Plants.Include(p => p.PlantImages).ToListAsync();
            return View(plants);
        }
        public async Task<IActionResult> Create()
        {
            ViewBag.Sizes = await _context.Sizes.ToListAsync();
            ViewBag.Colors = await _context.Colors.ToListAsync();
            ViewBag.Categories = await _context.Categories.ToListAsync();

            return View();
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Create(Plant plant)
        {
            ViewBag.Sizes = await _context.Sizes.ToListAsync();
            ViewBag.Colors = await _context.Colors.ToListAsync();
            ViewBag.Categories = await _context.Categories.ToListAsync();
            if (!ModelState.IsValid) return View();

            if (plant.MainImage == null || plant.AnotherImage == null)
            {
                ModelState.AddModelError("", "Please choose main image or another image");
                return View();
            }
            if (!plant.MainImage.IsOkay(1))
            {
                ModelState.AddModelError("MainImage", "Please choose  image file and max 1Mb ");
                return View();
            }
            foreach (var img in plant.AnotherImage)
            {
                if (!img.IsOkay(1))
                {
                    ModelState.AddModelError("AnotherImage", "Please choose  image file and min 1Mb ");
                    return View();
                }
            }


            plant.PlantImages = new List<PlantImage>();
            PlantImage mainImage = new PlantImage
            {
                ImagePath = await plant.MainImage.FileCreate(_env.WebRootPath,"assets/images/website-images"),
                IsMain=true,
                Plant=plant

            };
            plant.PlantImages.Add(mainImage);


            foreach (var img in plant.AnotherImage)
            {
                PlantImage anotherimage = new PlantImage
                {
                    ImagePath = await img.FileCreate(_env.WebRootPath, "assets/images/website-images"),
                    IsMain = false,
                    Plant = plant

                };
                plant.PlantImages.Add(anotherimage);
            }
            plant.PlantCategories = new List<PlantCategory>();

            foreach (var id in plant.CategoryIds)
            {
                PlantCategory plantCategory = new PlantCategory
                {
                    Plant = plant,
                    CategoryId = id
                };
            }

            await _context.Plants.AddAsync(plant);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.Sizes = await _context.Sizes.ToListAsync();
            ViewBag.Colors = await _context.Colors.ToListAsync();
            ViewBag.Categories = await _context.Categories.ToListAsync();
            Plant plant =await _context.Plants.Include(p=>p.PlantImages).FirstOrDefaultAsync(p=>p.Id==id);
            return View(plant);
        }


        [HttpPost]
        [AutoValidateAntiforgeryToken]

        public async Task<IActionResult> Edit(Plant plant ,int id)
        {

            ViewBag.Sizes = await _context.Sizes.ToListAsync();
            ViewBag.Colors = await _context.Colors.ToListAsync();
            ViewBag.Categories = await _context.Categories.ToListAsync();

            Plant existed = await _context.Plants.Include(p => p.PlantImages).FirstOrDefaultAsync(p=>p.Id==id);
            if (existed == null) return NotFound();

            if (plant.ImageIds==null && plant.AnotherImage ==null)
            {
                ModelState.AddModelError("", "You can not empty images");
                return View(existed);
            }

            List<PlantImage> removaebleImages = existed.PlantImages.Where(p => p.IsMain == false && !plant.ImageIds.Contains(p.Id)).ToList();

            existed.PlantImages.RemoveAll(p => removaebleImages.Any(ri => ri.Id == p.Id));

            foreach (var image in removaebleImages)
            {
                FileUtilities.FileDelete(_env.WebRootPath, @"assets\images\website-images", image.ImagePath);
            }

            foreach (var image in plant.AnotherImage)
            {
                PlantImage plantImage = new PlantImage
                {
                    ImagePath = await image.FileCreate(_env.WebRootPath,@"assets\images\website-images"),
                    IsMain = false,
                    PlantId = existed.Id
                };
                existed.PlantImages.Add(plantImage);
            }
            _context.Entry(existed).CurrentValues.SetValues(plant);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Detail(int id)
        {
            ViewBag.Sizes = await _context.Sizes.ToListAsync();
            ViewBag.Colors = await _context.Colors.ToListAsync();
            Plant plant = await _context.Plants.Include(p => p.PlantImages).FirstOrDefaultAsync(p => p.Id == id);
            return View(plant);
        }
        public async Task<IActionResult> Delete(int id)
        {
            ViewBag.Sizes = await _context.Sizes.ToListAsync();
            ViewBag.Colors = await _context.Colors.ToListAsync();
            Plant plant = await _context.Plants.Include(p => p.PlantImages).FirstOrDefaultAsync(p => p.Id == id);
            return View(plant);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeletePlant( Plant plant,int id)
        {
            ViewBag.Sizes = await _context.Sizes.ToListAsync();
            ViewBag.Colors = await _context.Colors.ToListAsync();
            plant = await _context.Plants.Include(p => p.PlantImages).FirstOrDefaultAsync(p => p.Id == id);
            if (plant == null) return NotFound();

            _context.Plants.Remove(plant);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

            PlantImage plantImage = new PlantImage();
            string Path = $"assets/images/website-images/{plantImage.ImagePath}";
            FileInfo file = new FileInfo(Path);
            if (file.Exists)
            {
                file.Delete();
            }
           
        }


    }
}

Ap204_Pronia/Areas/ProniaAdmin/Views/Plant/Create.cshtml
@model Plant
@{
    ViewData["Title"] = "Create";
}

<div asp-validation-summary="ModelOnly" class=" alert alert-danger"></div>
<form method="post" enctype="multipart/form-data">
    <div>
        <label class="mb-3">Plant  Name:</label><br />
        <input asp-for="Name" class="form-control border border-info" /><br />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div>
        <label class="mb-3">Plant Price:</label><br />
        <input asp-for="Price" class="form-control border border-info" /><br />
        <span class="text-danger" asp-validation-for="Price"></span>
    </div>
    <div>
        <label class="mb-3">Plant Description:</label><br />
        <input asp-for="Description" class="form-control border border-info" /><br />
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>
    <div>
        <label class="mb-3">Plant SkuCode:</label><br />
        <input asp-for="SKUCode" class="form-control border border-info" /><br />
        <span class="text-danger" asp-validation-for="SKUCode"></span>
    </div>
    <div>
        <label class="mb-3">Plant Colors:</label><br />
        <select class="form-select" asp-items="@(new SelectList(ViewBag.Colors,"Id","Name"))" asp-for="ColorId">
        </select>
        <span class="text-danger" asp-validation-for="SKUCode"></span>
    </div>
    <div>
        <label class="mb-3">Plant Sizes:</label><br />
        <select class="form-select" asp-items="@(new SelectList(ViewBag.Sizes,"Id","Name"))" asp-for="SizeId">
        </select>
        <span class="text-danger" asp-validation-for="SKUCode"></span>
    </div>
    <div>
        <label class="mb-3">Plant Categories:</label><br />
        <select class="form-select" asp-items="@(new SelectList(ViewBag.Categories,"Id","Name"))" asp-for="CategoryIds">
        </select>
        <span class="text-danger" asp-validation-for="CategoryIds"></span>
    </div>
     
    <div>
        <label class="mb-3">Plant Shipping:</label><br />
        <input asp-for="Shipping" class="form-control border border-info" /><br />
        <span class="text-danger" asp-validation-for="Shipping"></span>
    </div>
    <div>
        <label class="mb-3">Plant Guarantee :</label><br />
        <input asp-for="Guarantee" class="form-control border border-info" accept="image/*" /><br />
        <span class="text-danger" asp-validation-for="Guarantee"></span>
    </div>
     <div>
        <label class="mb-3">Plant MainImage :</label><br />
        <input asp-for="MainImage" class="form-control border border-info" accept="image/*" /><br />
        <span class="text-danger" asp-validation-for="MainImage"></span>
    </div>
     <div>
        <label class="mb-3">Plant AnotherImage :</label><br />
        <input asp-for="AnotherImage" class="form-control border border-info" accept="image/*" /><br />
        <span class="text-danger" asp-validation-for="AnotherImage"></span>
    </div>

    <div class="mt-3">
        <button type="submit" class="btn btn-primary">Create Plant</button>
    </div>
</form>

Ap204_Pronia/Areas/ProniaAdmin/Views/Plant/Delete.cshtml
@model Plant
@{
    ViewData["Title"] = "Delete";
}

<div asp-validation-summary="ModelOnly" class=" alert alert-danger"></div>
<form method="post" enctype="multipart/form-data">
    <div>
        <label class="mb-3">Plant  Name:</label><br />
        <input asp-for="Name" class="form-control border border-info" /><br />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div>
        <label class="mb-3">Plant Price:</label><br />
        <input asp-for="Price" class="form-control border border-info" /><br />
        <span class="text-danger" asp-validation-for="Price"></span>
    </div>
    <div>
        <label class="mb-3">Plant Description:</label><br />
        <input asp-for="Description" class="form-control border border-info" /><br />
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>
    <div>
        <label class="mb-3">Plant SkuCode:</label><br />
        <input asp-for="SKUCode" class="form-control border border-info" /><br />
        <span class="text-danger" asp-validation-for="SKUCode"></span>
    </div>
    <div>
        <label class="mb-3">Plant Colors:</label><br />
        <select class="form-select" asp-items="@(new SelectList(ViewBag.Colors,"Id","Name"))" asp-for="ColorId">
        </select>
        <span class="text-danger" asp-validation-for="SKUCode"></span>
    </div>
    <div>
        <label class="mb-3">Plant Sizes:</label><br />
        <select class="form-select" asp-items="@(new SelectList(ViewBag.Sizes,"Id","Name"))" asp-for="SizeId">
        </select>
        <span class="text-danger" asp-validation-for="SKUCode"></span>
    </div>
     
    <div>
        <label class="mb-3">Plant Shipping:</label><br />
        <input asp-for="Shipping" class="form-control border border-info" /><br />
        <span class="text-danger" asp-validation-for="Shipping"></span>
    </div>
    <div>
        <label class="mb-3">Plant Guarantee :</label><br />
        <input asp-for="Guarantee" class="form-control border border-info" accept="image/*" /><br />
        <span class="text-danger" asp-validation-for="Guarantee"></span>
    </div>
     
     <div>
        <label class="mb-3">Plant Main Image :</label><br />
        <img style=" width:150px; height:90px;" src="~/assets/images/website-images/@Model.PlantImages.FirstOrDefault(i=>i.IsMain==false).ImagePath"/>
        <span class="text-danger" asp-validation-for="MainImage"></span>
    </div>

    <p>Another Image</p>
    <div class="d-fex">
        @foreach (var img in Model.PlantImages.Where(i=>i.IsMain==false))
       {
             <div class="col-lg-2">
        <img style=" width:150px; height:90px;" src="~/assets/images/website-images/@img.ImagePath"/>

             </div>
       }
    </div>
     <div class="mt-3">
        <button type="submit" class="btn btn-warning">Delete Plant</button>
    </div>
</form>

Ap204_Pronia/Areas/ProniaAdmin/Views/Plant/Detail.cshtml
@model Plant
@{
    ViewData["Title"] = "Edit";
}

<div asp-validation-summary="ModelOnly" class=" alert alert-danger"></div>
<form method="post" enctype="multipart/form-data">
    <div>
        <label class="mb-3">Plant  Name:</label><br />
        <input asp-for="Name" class="form-control border border-info" /><br />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div>
        <label class="mb-3">Plant Price:</label><br />
        <input asp-for="Price" class="form-control border border-info" /><br />
        <span class="text-danger" asp-validation-for="Price"></span>
    </div>
    <div>
        <label class="mb-3">Plant Description:</label><br />
        <input asp-for="Description" class="form-control border border-info" /><br />
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>
    <div>
        <label class="mb-3">Plant SkuCode:</label><br />
        <input asp-for="SKUCode" class="form-control border border-info" /><br />
        <span class="text-danger" asp-validation-for="SKUCode"></span>
    </div>
    <div>
        <label class="mb-3">Plant Colors:</label><br />
        <select class="form-select" asp-items="@(new SelectList(ViewBag.Colors,"Id","Name"))" asp-for="ColorId">
        </select>
        <span class="text-danger" asp-validation-for="SKUCode"></span>
    </div>
    <div>
        <label class="mb-3">Plant Sizes:</label><br />
        <select class="form-select" asp-items="@(new SelectList(ViewBag.Sizes,"Id","Name"))" asp-for="SizeId">
        </select>
        <span class="text-danger" asp-validation-for="SKUCode"></span>
    </div>
     
    <div>
        <label class="mb-3">Plant Shipping:</label><br />
        <input asp-for="Shipping" class="form-control border border-info" /><br />
        <span class="text-danger" asp-validation-for="Shipping"></span>
    </div>
    <div>
        <label class="mb-3">Plant Guarantee :</label><br />
        <input asp-for="Guarantee" class="form-control border border-info" accept="image/*" /><br />
        <span class="text-danger" asp-validation-for="Guarantee"></span>
    </div>
     
     <div>
        <label class="mb-3">Plant Main Image :</label><br />
        <img style=" width:150px; height:90px;" src="~/assets/images/website-images/@Model.PlantImages.FirstOrDefault(i=>i.IsMain==true).ImagePath"/>
        <span class="text-danger" asp-validation-for="AnotherImage"></span>
    </div>

    <p>Another Image</p>
    <div class="d-fex">
        @foreach (var img in Model.PlantImages.Where(i=>i.IsMain==false))
       {
             <div class="col-lg-2">
        <img style=" width:150px; height:90px;" src="~/assets/images/website-images/@img.ImagePath"/>

             </div>
       }
    </div>

</form>

Ap204_Pronia/Areas/ProniaAdmin/Views/Plant/Edit.cshtml
@model Plant
@{
    ViewData["Title"] = "Edit";
}

<div asp-validation-summary="ModelOnly" class=" alert alert-danger"></div>
<form method="post" enctype="multipart/form-data">
    <div>
        <label class="mb-3">Plant  Name:</label><br />
        <input asp-for="Name" class="form-control border border-info" /><br />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div>
        <label class="mb-3">Plant Price:</label><br />
        <input asp-for="Price" class="form-control border border-info" /><br />
        <span class="text-danger" asp-validation-for="Price"></span>
    </div>
    <div>
        <label class="mb-3">Plant Description:</label><br />
        <input asp-for="Description" class="form-control border border-info" /><br />
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>
    <div>
        <label class="mb-3">Plant SkuCode:</label><br />
        <input asp-for="SKUCode" class="form-control border border-info" /><br />
        <span class="text-danger" asp-validation-for="SKUCode"></span>
    </div>
    <div>
        <label class="mb-3">Plant Colors:</label><br />
        <select class="form-select" asp-items="@(new SelectList(ViewBag.Colors,"Id","Name"))" asp-for="ColorId">
        </select>
        <span class="text-danger" asp-validation-for="SKUCode"></span>
    </div>
    <div>
        <label class="mb-3">Plant Sizes:</label><br />
        <select class="form-select" asp-items="@(new SelectList(ViewBag.Sizes,"Id","Name"))" asp-for="SizeId">
        </select>
        <span class="text-danger" asp-validation-for="SKUCode"></span>
    </div>

    <div>
        <label class="mb-3">Plant Shipping:</label><br />
        <input asp-for="Shipping" class="form-control border border-info" /><br />
        <span class="text-danger" asp-validation-for="Shipping"></span>
    </div>
    <div>
        <label class="mb-3">Plant Guarantee :</label><br />
        <input asp-for="Guarantee" class="form-control border border-info" accept="image/*" /><br />
        <span class="text-danger" asp-validation-for="Guarantee"></span>
    </div>
    <div>
        <label class="mb-3">Plant MainImage :</label><br />
        <input asp-for="MainImage" class="form-control border border-info" accept="image/*" /><br />
        <span class="text-danger" asp-validation-for="MainImage"></span>
    </div>
    <div>
        <label class="mb-3">Plant AnotherImage :</label><br />
        <input asp-for="AnotherImage" class="form-control border border-info" accept="image/*" /><br />
        <span class="text-danger" asp-validation-for="AnotherImage"></span>
    </div>

    <span class="mb-3">Plant Main Image :</span><br />
    <div style="position:relative">
        <i class="mdi mdi-close closebtn" style="position:absolute;color:red ;font-size:20px;"> </i>
        <img style=" width:150px; height:90px;" src="~/assets/images/website-images/@Model.PlantImages.FirstOrDefault(i=>i.IsMain==true).ImagePath" />
        <span class="text-danger" asp-validation-for="MainImage"></span>
        <input type="hidden" value="@@Model.PlantImages.FirstOrDefault(i=>i.IsMain==true).Id" name= "ImageIds"/>
    </div>

    <p>Another Image</p>
    <div class="d-fex">
        @foreach (var img in Model.PlantImages.Where(i => i.IsMain == false))
        {
            <div class="col-lg-2" style="position:relative">
                <i class="mdi mdi-close closebtn" style="position:absolute;color:red ;font-size:20px;"> </i>
                <img style=" width:150px; height:90px;" src="~/assets/images/website-images/@img.ImagePath" />
                <input type="hidden" value="@img.Id" name= "ImageIds"/>
            </div>
        }
    </div>

    <div class="mt-3">
        <button type="submit" class="btn btn-primary">Edit Plant</button>
    </div>
</form>
@section Scripts{
<script>


    $(".closebtn").click(function(){
        this.parentNode.remove();
    })
    $(".closebtn").click(function(){
        this.parentNode.remove();
    })


</script>
}

Ap204_Pronia/Areas/ProniaAdmin/Views/Plant/Index.cshtml
@model List<Plant>

    <div class="table-responsive pt-3">
    <a asp-controller="Plant" asp-action="Create" style="color:white;font-size:20px" class="mb-3 btn btn-success">Create Plant</a>
    <table class="table table-dark">
        <thead>
            <tr>
                <th>
                    Image
                </th>
                <th>
                    Name
                </th>
                <th>
                    Price
                </th>
                <th>
                    Color
                </th>
                <th>
                    Settings
                </th>

            </tr>
        </thead>
        <tbody>
            @foreach (Plant pl in Model)
            {
                <tr>
                    <td>
                        <img style="width: 150px; height:90px" src="~/assets/images/website-images/@pl.PlantImages.FirstOrDefault().ImagePath" />
                   </td>
                    <td>
                        @pl.Name
                    </td>
                    <td>
                      
                        @pl.Price
                       
                    </td>
                    <td>
                        @pl.Color
                    </td>
                    <td>
                        <div class="d-flex">
                            <div class="detail">
                                <a asp-controller="Plant" asp-action="Detail" asp-route-id="@pl.Id" class="btn btn-primary"><i class="mdi mdi-details"></i></a>
                            </div>
                            <div class="edit">
                                <a asp-controller="Plant" asp-action="Edit" asp-route-id="@pl.Id" class="btn btn-warning">
                                    <i class="mdi mdi-tooltip-edit"></i>
                                </a>
                            </div>
                            <div class="delete">
                                <a asp-controller="Plant" asp-action="Delete" asp-route-id="@pl.Id" class="btn btn-danger"> <i class="mdi mdi-delete-forever"></i></a>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>