Ap204_Pronia/Models/Size.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;



namespace Ap204_Pronia.Models
{
    public class Size
    {
        public int Id { get; set; }
        [StringLength(maximumLength: 10, ErrorMessage = "You can write maximum 10 charachter")]
        public string Name { get; set; }

        public List<Plant> Plants { get; set; }

        
    }
}

Ap204_Pronia/Areas/ProniaAdmin/Controllers/SizeController.cs
using Ap204_Pronia.DAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Drawing;
using System.Threading.Tasks;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace Ap204_Pronia.Areas.ProniaAdmin.Controllers
{

    [Area("ProniaAdmin")]

    public class SizeController : Controller
    {
        private readonly AppDbContext _context;

        public SizeController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            List<Models.Size> sizes = await _context.Sizes.ToListAsync();
            return View(sizes);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Models.Size size)
        {
            if (!ModelState.IsValid) return View();
            await _context.Sizes.AddAsync(size);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Detail(int id)
        {
           Models.Size size = await _context.Sizes.FirstOrDefaultAsync(s => s.Id == id);
            if (size == null) return NotFound();
            return View(size);
        }

        public async Task<IActionResult> Edit(int id)
        {
            Models.Size size = await _context.Sizes.FirstOrDefaultAsync(s => s.Id == id);
            if (size == null) return NotFound();
            return View(size);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Edit(int id, Models.Size size)
        {
            
            Models.Size existedSize = await _context.Sizes.FirstOrDefaultAsync(s => s.Id == id);
            if (existedSize == null) return NotFound();
            if (id != size.Id) return BadRequest();

            existedSize.Name = size.Name;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Delete(int id)
        {
            Models.Size size = await _context.Sizes.FirstOrDefaultAsync(s => s.Id == id);
            if (size == null) return NotFound();
            return View(size);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteSize(int id)
        {
            Models.Size size = await _context.Sizes.FirstOrDefaultAsync(s => s.Id == id);
            if (size == null) return NotFound();

            _context.Sizes.Remove(size);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }

}

Ap204_Pronia/Areas/ProniaAdmin/Views/Size/Create.cshtml
@using Ap204_Pronia.Models
@model Size
@{
    ViewData["Title"] = "Create";
}

<form method="post" class="form form-control mb-3">
   <div>
     <label class="mb-2" >Size Name:</label>
    <input asp-for="Name" class="form form-control border border-info mb-2" type="text"/>
    <span class="text-danger" asp-validation-for="Name"></span>
   </div>
   <div>
       <button type="submit" class="btn btn-dark"> Create Size</button>
   </div>
</form>

Ap204_Pronia/Areas/ProniaAdmin/Views/Size/Delete.cshtml
@using Ap204_Pronia.Models;

@{
    ViewData["Title"] = "Delete";
}

<div>
    <div>
        <h4>
            Id
        </h4>
        <p>
            @Model.Id
        </p>
    </div>
    <div>
        <h4>
            Name
        </h4>
        <p>
            @Model.Name
        </p>
    </div>
</div>


<form method="post" class="mt-4">
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

Ap204_Pronia/Areas/ProniaAdmin/Views/Size/Detail.cshtml
@using Ap204_Pronia.Models
@model Size
@{
    ViewData["Title"] = "Detail";
}
<div>
    <div>
        <h2>Id:  @Model.Id</h2>
      
    </div>
    <div>
         <h2>Name:   @Model.Name </h2>
       
    </div>
</div>

Ap204_Pronia/Areas/ProniaAdmin/Views/Size/Edit.cshtml
@using Ap204_Pronia.Models
@model Size
@{
    ViewData["Title"] = "Edit";
}

<form method="post" class="form form-control mb-3">
   <div>
     <label class="mb-2" >Size Name:</label>
    <input asp-for="Name" class="form form-control border border-info mb-2" type="text"/>
    <span class="text-danger" asp-validation-for="Name"></span>
   </div>
   <div>
       <button type="submit" class="btn btn-dark"> Edit Size</button>
   </div>
</form>

Ap204_Pronia/Areas/ProniaAdmin/Views/Size/Index.cshtml
@using Ap204_Pronia.Models
@model List<Size>
@{
    ViewData["Title"] = "Index";
}


<div class="table-responsive pt-3">
    <a asp-controller="Size" asp-action="create" style="color:white;font-size:20px" class="mb-3 btn btn-success">Create size</a>
    <table class="table table-dark">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Name
                </th>
                <th>
                    Settings
                </th>

            </tr>
        </thead>
        <tbody>
            @foreach (Size size in Model)
            {
                <tr>
                    <td>
                        @size.Id
                    </td>
                    <td>
                        @size.Name
                    </td>
                    <td>
                        <div class="d-flex">
                            <div class="detail">
                                <a asp-controller="Size" asp-action="Detail" asp-route-id="@size.Id" class="btn btn-primary"><i class="mdi mdi-details"></i></a>
                            </div>
                            <div class="edit">
                                <a asp-controller="Size" asp-action="Edit" asp-route-id="@size.Id" class="btn btn-warning">
                                    <i class="mdi mdi-tooltip-edit"></i>
                                </a>
                            </div>
                            <div class="delete">
                                <a asp-controller="Size" asp-action="Delete" asp-route-id="@size.Id" class="btn btn-danger"> <i class="mdi mdi-delete-forever"></i></a>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>